<!DOCTYPE html>
<html lang="en">
<head>
<?php echo $this->headTitle(); ?>
<?php echo $this->headLink(); ?>
<?php echo $this->headStyle(); ?>
<?php echo $this->headMeta(); ?>
<?php echo $this->headScript(); ?>

</head>

<body>
    
    <?php echo $this->menu(); ?>

    <div class="container">
        <div class="row-fluid">
            <div class="span12">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </div>
</body>
</html>