<div class="hero-unit">
    <h1><?php echo sprintf($this->translate('Welcome to %sAdapto%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sAdapto Skeleton Application%s. You are currently running Adapto version %s. This skeleton can serve as a simple starting point for you to begin building your application on top of Adapto. '), '<a href="https://github.com/egeniq/adapto" target="_blank">', '</a>', \Adapto\About::VERSION) ?></p>
    <p><?php echo sprintf($this->translate('Adapto is a Rapid Application Development framework for data management applications built on top of %sZend Framework 2%.'), '<a href="http://github.com/zendframework/zf2">', '</a>'); ?>
    <p><a class="btn btn-success btn-large" href="https://github.com/egeniq/adapto" target="_blank"><?php echo $this->translate('Fork Adapto on GitHub') ?> &raquo;</a></p>
</div>
